[net]
tickrate = 30
port = 1212
max_connections = 256

[status]
enabled = true
connectaddress = "udp://aurorasong.gay:1212"

[whitelist]
enabled = true

[game]
hostname = "[18+][MRP] Aurora's Song"
soft_max_players = 100

[ic]
restricted_names = false

[shuttle]
auto_call_time = 2880

[atmos]
delta_pressure_damage = false
space_wind = false

[hub]
advertise = false
tags = ""
server_url = "ss14s://aurorasong.gay/game"
hub_urls="https://hub.playss14.com/"

[auth]
mode = 1
server="https://auth.playss14.com/"

[npc]
player_pause_distance = 40

[nf14.respawn]
time = 20

[nf14.gc]
idle_count = 1
period = 300

[infolinks]
discord    = "https://discord.gg/aurorasong"
github     = "https://github.com/AuroraSong14/Aurora-Song-14"
wiki       = "https://wiki.aurorasong.gay/index.php?title=Main_Page"
bug_report = "https://github.com/AuroraSong14/Aurora-Song-14/issues"
