using System.Text;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Content.Shared._AS.Forensics;

// All of this is based upon the WakeScannerMenu.xaml.cs, which has been trimmed down and configured the new use case.
namespace Content.Client._AS.Forensics
{
    [GenerateTypedNameReferences]
    public sealed partial class WakeScannerMenu : DefaultWindow
    {
        [Dependency] private readonly IGameTiming _gameTiming = default!;

        public WakeScannerMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
        }

        public void UpdatePrinterState(bool disabled)
        {
            Print.Disabled = disabled;
        }

        public void UpdateState(WakeScannerBoundUserInterfaceState msg)
        {
            if (string.IsNullOrEmpty(msg.LastScannedName))
            {
                Print.Disabled = true;
                Clear.Disabled = true;
                NameLabel.Text = string.Empty;
                Diagnostics.Text = string.Empty;
                return;
            }

            Print.Disabled = (msg.PrintReadyAt > _gameTiming.CurTime);
            Clear.Disabled = false;

            NameLabel.Text = msg.LastScannedName;

            var text = new StringBuilder();

            text.AppendLine(Loc.GetString("forensic-scanner-interface-fingerprints"));
            text.AppendLine(msg.Signatures);
            text.AppendLine();
            text.AppendLine(Loc.GetString("forensic-scanner-interface-fibers"));
            text.AppendLine(msg.Destinations.ToString());
            Diagnostics.Text = text.ToString();
        }
    }
}
