- type: entity
  id: ThrusterMedicMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: SLE thruster machine board
  components:
  - type: Sprite
    state: medical
  - type: MachineBoard
    prototype: ThrusterMedic
    requirements:
      Capacitor: 3
    stackRequirements:
      Steel: 5

- type: entity
  id: ASTechFabSLECircuitboard
  parent: SecurityTechFabCircuitboard
  name: SLE techfab machine board
  description: A machine printed circuit board for an SLE techfab.
  components:
    - type: Sprite
      sprite: _AS/Objects/Misc/module.rsi
      state: sle
    - type: MachineBoard
      prototype: ASTechFabSLE

  parent: BaseMachineCircuitboard
  id: MobileWakeAnalyzerMachineCircuitboard
  name: mobile wake analyzer machine board
  description: A machine printed circuit board for a mobile wake analyzer.
  components:
  - type: Sprite
    sprite: _NF/Objects/Misc/module.rsi
    state: nfsd
  - type: MachineBoard
    prototype: MobileWakeAnalyzer
    requirements:
      Capacitor: 4
    stackRequirements:
      Steel: 5
      Cable: 2